name: Build KivyMD Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install buildozer
        pip install kivy==2.3.0 kivymd==1.1.1 pillow

    - name: Configure Buildozer
      run: |
        echo "Buildozer configuration check complete."

    - name: Build Android APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MdSamiulProthomApp-APK
        path: bin/*.apk

    - name: Notify on completion
      run: echo "APK build process completed. Check artifacts for the APK file."

